### ISSUE TITLE
COCO instances for missing images

### ISSUE THREAD

**Issue by biswassanket** [THEFASHIONGEEK/Document-Layout-Detection#3]
Hi,

I ran your code and found that your script generates COCO instances in json file for missing file names, I think there's a bug. Could you please look into this?

**Comment by THEFASHIONGEEK** [comment]
Hi,
 
you can check out this notebook [link](https://github.com/Tessellate-Imaging/Monk_Object_Detection/blob/master/application_model_zoo/Example%20-%20Document%20Layout%20Analysis%20(FasterRCNN).ipynb).
